---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
    tag: latest
inputs:
- name: control-tower
- name: binary-linux

run:
  path: control-tower/ci/tasks/system-test.sh

params:
  GOOGLE_APPLICATION_CREDENTIALS_CONTENTS: ((system_test_google_application_credentials))
  IAAS: GCP
  BINARY_PATH: binary-linux/control-tower-linux-amd64
  VERBOSE: true
  SKIP_TEARDOWN: true
